version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL = "postgresql+psycopg2://ourinhos:.py8Y;Ld'bk2u*>D@34.67.188.220:5433/ourinhos"
